config/routes.rb
Rails.application.routes.draw do

  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  root to: 'pages#home'

  resources :contacts

  resources :work_requests

  post '/work_requests/:id', to: "work_requests#accept_request"

  post '/reject', to: 'work_requests#reject_request'

  get '/awaiting_approval', to: 'work_requests#awaiting_approval'

  get '/summary', to: 'work_requests#summary'

  get '/change_status/:id', to: 'work_requests#change_status'

  resource :notes, except: [:index, :destroy, :show, :update]

  resources :data_submissions, except: [:index, :destroy]

  resources :notifications, except: [:destroy, :show]

end

app/models/work_request.rb
class WorkRequest < ApplicationRecord
  belongs_to :user
  has_one :data_submission
  has_many :notes
  has_many :notifications

  validates :scheme_name, :submission_date, :report_date, :issue_method, :project_type, :office, :status, presence: true

end

app/controllers/work_requests_controller.rb
class WorkRequestsController < ApplicationController

  def index
    if current_user
      @user = User.find(current_user.id)
    else
      flash[:alert] = "You must be logged in to access this page"
      redirect_to 'root_path'
    end
  end

  def new
    @work_request = WorkRequest.new
  end

  def create
    @work_request = WorkRequest.new(params.require(:work_request).permit(:scheme_name,
       :submission_date, :report_date, :issue_method, :project_type, :office))
    @work_request.user = current_user
    @work_request.status = "Awaiting Approval"
    if @work_request.save
      @work_request.data_submission = DataSubmission.create(work_request_id: @work_request.id)
      flash[:notice] = "Request successfully created"
      redirect_to work_requests_path
    else
      render 'new'
    end
  end

  def show
    @work_request = WorkRequest.find(params[:id])
    @note = Note.new
  end

  def edit
    @work_request = WorkRequest.find(params[:id])
  end

  def update
    @work_request = WorkRequest.find(params[:id])
    if @work_request.update(params.require(:work_request).permit(:status, :scheme_name,
        :submission_date, :report_date, :issue_method, :project_type, :office))
      flash[:notice] = "Request successfully amended"
      redirect_to work_requests_path
    else
       render 'edit'
    end
  end

  def awaiting_approval
    @work_requests = WorkRequest.where(request_approved: false, request_rejected: false)
  end

  def accept_request
    if current_user.analyst?
      @work_request = WorkRequest.find(params[:id])
      @work_request.request_approved = true
      @work_request.time_approved = DateTime.current
      @work_request.approved_by = Etc.getlogin
      @work_request.status = "Confirmed - awaiting submission"
      @work_request.update(params.permit(:request_approved, :time_approved, :approved_by, :status))
      new_notification(@work_request, false)
      flash[:notice] = "Request successfully confirmed"
      redirect_to awaiting_approval_path
    else
      flash[:alert] = "You do not have permission to access this page"
      redirect_to awaiting_approval_path
    end
  end

  def reject_request
    if current_user.analyst?
      @work_request = WorkRequest.find(params[:id])
      @work_request.request_rejected = true
      @work_request.time_rejected = DateTime.current
      @work_request.rejected_by = Etc.getlogin
      @work_request.status = "Rejected"
      @work_request.update(params.permit(:request_rejected, :time_rejected, :rejected_by, :status))
      new_notification(@work_request, false)
      flash[:notice] = "Request successfully rejected"
      redirect_to awaiting_approval_path
    else
      flash[:alert] = "You do not have permission to access this page"
      redirect_to awaiting_approval_path
    end
  end

  def summary
    if current_user.analyst?
      @work_requests = WorkRequest.where(request_approved: true)
    else
      flash[:alert] = "You do not have permission to access this page"
      redirect_to root_path
    end
  end

  def destroy
    @work_request = WorkRequest.find(params[:id])
    @work_request.destroy
    new_notification(@work_request, true)
    flash[:notice] = "Request successfully withdrawn"
    redirect_to work_requests_path
  end
end

app/views/work_requests/_analyst_edit_form.html.erb
<div class="card mb-2">
<%= form_for @work_request do |f| %>
<div class="card-header">
  <h3>
    <div class="">
      <%= @work_request.scheme_name %>
    </div>
    ID: <%= @work_request.id %>
  </h3>
</div>
  <div class="card-body">
    Submission date :
    <%= f.text_field :submission_date, id: 'submission_date' %>
    <br>
    <%= f.label :report_date %>
    <%= f.text_field :report_date, id: 'report_date' %>
    <br>
    <%= f.label :issue_method %>
    <%= f.text_field :issue_method, id: 'issue_method', disabled: true %>
  </div>
  <div class="card-body">
    <%= f.label :project_type %>
    <%= f.text_field :project_type, id: 'project_type', disabled: true %>
  </div>
  <div class="card-body">
    <%= f.label :office %>
    <%= f.text_field :office, id: 'office' %>
  </div>
  <div class="card-body">
    <%= f.label :status %>
    <%= f.text_field :status, id: 'status' %>
  </div>
  <div class="mb-4">
    <%= f.submit(@work_request.new_record? ? "Create request" : "Amend request") %>
  </div>
<% end %>
</div>

app/views/work_requests/_form.html.erb
<div class="card mb-2">
  <%= form_for @work_request do |f| %>
    <% if current_user.analyst? %>
      <div class="card-header mb-2">
        <h3>
          <div class="">
            <%= @work_request.scheme_name %> |
            ID: <%= @work_request.id %>
          </div
        </h3>
      </div>
    <% else %>
      <div class="input-group mb-3">
        <span class="input-group-text w-10" style="width: 150px;">Scheme name</span>
        <%= f.text_field :scheme_name, id: 'scheme_name', class: "form-control" %>
      </div>
    <% end %>
    <% if current_user.analyst? %>
    <div class="input-group mb-3">
      <span class="input-group-text w-10" style="width: 150px;">Status</span>
      <%= f.select :status, ["Data submitted", "Requires further analysis", "Further information required"],
                          id: 'status', class: "form-control" %>
    </div>
    <% end %>
    <div class="input-group mb-3">
      <span class="input-group-text w-10" style="width: 150px;">Submission date</span>
      <%= f.text_field :submission_date, id: 'submission_date', class: "form-control" %>
    </div>
    <div class="input-group mb-3">
      <span class="input-group-text w-10" style="width: 150px;">Report date</span>
      <%= f.text_field :report_date, id: 'report_date', class: "form-control" %>
    </div>
    <div class="input-group mb-3">
      <span class="input-group-text w-10" style="width: 150px;">Issue method</span>
      <%= f.text_field :issue_method, id: 'issue_method', class: "form-control" %>
    </div>
    <div class="input-group mb-3">
      <span class="input-group-text w-10" style="width: 150px;">Project type</span>
      <%= f.text_field :project_type, id: 'project_type', class: "form-control" %>
    </div>
    <div class="input-group mb-3">
      <span class="input-group-text w-10" style="width: 150px;">Office</span>
      <%= f.text_field :office, id: 'office', class: "form-control" %>
    </div>
    <div class="mb-4">
      <%= f.submit(@work_request.new_record? ? "Create request" : "Amend request", class: "btn btn-dark") %>
      <%= link_to "Cancel", :back, class: "btn btn-dark" %>
    </div>
</div>

  <% end %>

app/views/work_requests/awaiting_approval.html.erb
<% @work_requests.each do |request| %>
  <div class="card mb-2 mt-2" style="width: 20rem;">
    <div class="card-title">
      <%= link_to request.scheme_name, work_request_path(request), class: "btn btn-dark" %> |
      ID: <%= request.id %>
    </div>
    <div class="">
      submitted by - <%= request.user.email %>
    </div>
    <div class="">
      Sub date - <%= request.submission_date %>
    </div>
    <div class="">
      Rep date - <%= request.report_date %>
    </div>
  </div>
<% end %>

app/views/work_requests/edit.html.erb
<h2>Amend request</h2>
<%= render 'layouts/errors', obj: @work_request %>
<%= render 'work_requests/form' %>

app/views/work_requests/index.html.erb
<div class="mt-2 mb-2">
  <%= link_to "New request", new_work_request_path, class: "btn btn-dark" %>
</div>
<% if @user.work_requests.any? %>
  <% @user.work_requests.each do |request| %>
    <div class="entry col-xs-4 col-xs-offset-0 col-lg-4 col-lg-offset-0">
      <div class="card mb-2" style="width: 20rem;">
        <div class="card-body">
          <h5 class="card-title">
            <div class="">
              <%= link_to request.scheme_name, work_request_path(request) %>
            </div>
            <div class="">
              ID: <%= request.id %>
            </div>
          </h5>
          <div class="card-subtitle mb-2 text-muted">
            Submission Date: <%= request.submission_date %>
          </div>
          <div class="card-subtitle mb-2 text-muted">
            Current Status: <%= request.status %>
          </div>
          <% if request.request_rejected == false %>
            <%= link_to "Amend request", edit_work_request_path(request), class: "btn btn-sm btn-dark mb-2" %> |
            <%= link_to "Withdraw Request",  work_request_path(request), method: :delete, data: { confirm: "Confirm"}, class: "btn btn-sm btn-dark mb-2" %>
            <div class="">
              <% if request.data_submission %>
                <%= link_to "Data Submission", data_submission_path(request.data_submission), class: "btn btn-sm btn-dark mb-2" %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/work_requests/new.html.erb
<h2>Create new request</h2>
<%= render 'layouts/errors', obj: @work_request %>
<%= render 'work_requests/form' %>

app/views/work_requests/show.html.erb
<div class="card mb-2">
  <div class="card-header">
    <h3>
      <div class="">
        <%= @work_request.scheme_name %>
      </div>
      ID: <%= @work_request.id %>
    </h3>
  </div>
  <div class="card-body">
    Status : <%= @work_request.status %>
    <br>
    Submitted by : <%= @work_request.user.email %>
  </div>
  <div class="card-body">
    <h5>Request dates</h5>
    <div class="card-text">
      Submission Date : <%= @work_request.submission_date %>
    </div>
    <div class="card-text">
      Report Date : <%= @work_request.report_date %>
    </div>
  </div>
  <div class="card-body">
    <h5>Request details</h5>
    <div class="card-text">
      Issue method : <%= @work_request.issue_method %>
    </div>
    <div class="card-text">
      Project type : <%= @work_request.project_type %>
    </div>
  </div>
</div>
<% if current_user.analyst? %>
  <% if !@work_request.request_approved? %>
    <%= link_to "Confirm request", work_request_path(@work_request), method: :post, class: "btn btn-sm btn-dark mb-2" %>
    <%= link_to "Reject request", { :controller => 'work_requests', :action => 'reject_request', :id => @work_request.id}, :method => :post, class: "btn btn-sm btn-dark mb-2" %>
  <% else %>
    <%= link_to "Amend request", edit_work_request_path(@work_request), class: "btn btn-sm btn-dark mb-2" %>
    <%= link_to "Cancel", :back, class: "btn btn-sm btn-dark mb-2" %>
  <% end %>
<% else %>
  <%= link_to "Amend request", edit_work_request_path(@work_request), class: "btn btn-sm btn-dark mb-4" %> |
  <%= link_to "Withdraw request", work_request_path(@work_request), method: :destroy, data: { confirm: "Confirm"}, class: "btn btn-sm btn-dark mb-2" %>
  <div class="">
    <%= link_to "Submit data", edit_data_submission_path(@work_request.data_submission), class: "btn btn-sm btn-dark mb-4" %>
    <%= link_to "Cancel", :back, class: "btn btn-sm btn-dark mb-2" %>
  </div>
<% end %>
<% if @work_request.notifications.any? %>
  <% @work_request.notifications.each do |notification| %>
    <% if !notification.viewed %>
      <div class="">
        <%= notification.message %>
        <%= link_to "Acknowledge notifcation", notification_path(notification), method: :patch, class: "btn btn-sm btn-dark mb-4" %>
      </div>
    <% end %>
  <% end %>
<% end %>
<div class="mt-4">
  <%= form_for @note do |f| %>
  <div class="input-group mb-3">
    <span class="input-group-text w-10" style="width: 150px;">Add note</span>
    <%= f.text_field :note, id: 'note', class: "form-control" %>
  </div>
  <div class="mb-4">
    <%= f.submit "Add note", class: "btn btn-dark" %>
    <%= hidden_field_tag :wr_id, @work_request.id %>
  </div>
  <% end %>
</div>
<div class="mb-4">
<% if @work_request.notes.any? %>
  <% @work_request.notes.each do |note| %>
    <div class="">
      <%= note.created_at %> - <%= note.note %>
    </div>
  <% end %>
<% end %>
</div>

app/views/work_requests/summary.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="column">
      <table class="table table-bordered">
        <thead>
          <th colspan="3">Awaiting data</th>
        </thead>
        <tr>
          <th>Scheme name</th>
          <th>Due date</th>
          <th>ID</th>
        <% @work_requests.each do |request| %>
          <% if request.status == "Confirmed - awaiting submission" && request.submission_date >= Date.today %>
            <tr>
              <td><%= request.scheme_name %></td>
              <td><%= request.submission_date %></td>
              <td><%= link_to request.id, work_request_path(request) %></td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
    <div class="column">
      <table class="table table-bordered">
        <thead>
          <th colspan="3">Data received</th>
        </thead>
        <tr>
          <th>Scheme name</th>
          <th>Due date</th>
          <th>ID</th>
        <% @work_requests.each do |request| %>
          <% if request.status == "Data submitted" %>
            <tr>
              <td><%= request.scheme_name %></td>
              <td><%= request.submission_date %></td>
              <td><%= link_to request.id, work_request_path(request) %></td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
    <div class="column">
      <table class="table table-bordered">
        <thead>
          <th colspan="3">Overdue data</th>
        </thead>
        <tr>
          <th>Scheme name</th>
          <th>Due date</th>
          <th>ID</th>
        <% @work_requests.each do |request| %>
          <% if request.status == "Confirmed - awaiting submission" && request.submission_date < Date.today %>
            <tr>
              <td><%= request.scheme_name %></td>
              <td><%= request.submission_date %></td>
              <td><%= link_to request.id, work_request_path(request) %></td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
    <div class="column">
      <table class="table table-bordered">
        <thead>
          <th colspan="3">Further information required</th>
        </thead>
        <tr>
          <th>Scheme name</th>
          <th>Due date</th>
          <th>ID</th>
        <% @work_requests.each do |request| %>
          <% if request.status == "Further information required" %>
            <tr>
              <td><%= request.scheme_name %></td>
              <td><%= request.submission_date %></td>
              <td><%= link_to request.id, work_request_path(request) %></td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
    <div class="column">
      <table class="table table-bordered">
        <thead>
          <th colspan="3">Requires further analysis</th>
        </thead>
        <tr>
          <th>Scheme name</th>
          <th>Due date</th>
          <th>ID</th>
        <% @work_requests.each do |request| %>
          <% if request.status == "Requires further analysis" %>
            <tr>
              <td><%= request.scheme_name %></td>
              <td><%= request.submission_date %></td>
              <td><%= link_to request.id, work_request_path(request) %></td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>
</div>