config/routes.rb
Rails.application.routes.draw do

  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  root to: 'pages#home'

  resources :contacts

  resources :work_requests

  post '/work_requests/:id', to: "work_requests#accept_request"

  post '/reject', to: 'work_requests#reject_request'

  get '/awaiting_approval', to: 'work_requests#awaiting_approval'

  get '/summary', to: 'work_requests#summary'

  get '/change_status/:id', to: 'work_requests#change_status'

  resource :notes, except: [:index, :destroy, :show, :update]

  resources :data_submissions, except: [:index, :destroy]

  resources :notifications, except: [:destroy, :show]

end

app/models/contact.rb
class Contact < ApplicationRecord
  # belongs_to :user

  before_save :email.downcase
  # before_save :first_name.capitalize, :last_name.capitalize

  validates :first_name, :last_name, :phone_number, :job_role, :email, presence: true

  validates :first_name, length: { minimum: 2, maximum: 35 }, if: -> { first_name.present? }
  validates :last_name, length: { minimum: 2, maximum: 35 }, if: -> { last_name.present? }
  validates :phone_number, length: { minimum: 5, maximum: 14 }, if: -> { phone_number.present? }
  validates :job_role, length: { minimum: 2, maximum: 35 }, if: -> { job_role.present? }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }, if: -> { email.present? }

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = Contact.all
  end

  def new
    if current_user && current_user.admin?
      @contact = Contact.new
    else
      flash[:alert] = "You do not have permission to access new contacts page"
      redirect_to root_path
    end
  end

  def create
    @contact = Contact.new(params.require(:contact).permit(:first_name, :last_name, :email, :phone_number, :job_role))
    if @contact.save
      flash[:alert] = "Contact added successfully"
      redirect_to contacts_path
    else
      render 'new'
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update(params.require(:contact).permit(:first_name, :last_name, :email, :phone_number, :job_role))
      flash[:alert] = "Contact updated successfully"
      redirect_to contacts_path
    else
      render 'edit'
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    flash[:alert] = "Contact deleted successfully"
    redirect_to contacts_path
  end
end

app/views/contacts/edit.html.erb
<h3 class="text-center">Edit contact</h3>
<%= render 'layouts/errors', obj: @contact %>
<%= render '/forms/contact_form' %>

app/views/contacts/index.html.erb
<div class="container">
  <% if current_user && current_user.admin? %>
    <%= link_to "Create contact", new_contact_path, class: "btn btn-danger mb-2 mt-2" %>
  <% else %>
    <div class="mb-2">
    </div>
  <% end %>
  <% @contacts.each do |contact| %>
    <div class="card mb-4" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%=contact.first_name %> <%=contact.last_name%></h5>
        <p class="card-text"><%= contact.job_role %></p>
        <p class="card-text"><%= contact.email %></p>
        <p class="card-text"><%= contact.phone_number %></p>
        <% if current_user && current_user.admin? %>
          <%= link_to "Edit", edit_contact_path(contact) %> |
          <%= link_to "Delete", contact_path(contact), data: { confirm: "Are you sure you would like to delete this contact?"}, method: :delete %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<h3 class="text-center">Create new contact</h3>
<%= render 'layouts/errors', obj: @contact %>
<%= render '/forms/contact_form' %>