config/routes.rb
Rails.application.routes.draw do

  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  root to: 'pages#home'

  resources :contacts

  resources :work_requests

  post '/work_requests/:id', to: "work_requests#accept_request"

  post '/reject', to: 'work_requests#reject_request'

  get '/awaiting_approval', to: 'work_requests#awaiting_approval'

  get '/summary', to: 'work_requests#summary'

  get '/change_status/:id', to: 'work_requests#change_status'

  resource :notes, except: [:index, :destroy, :show, :update]

  resources :data_submissions, except: [:index, :destroy]

  resources :notifications, except: [:destroy, :show]

end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<nav class="navbar fixed-bottom navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Contact", contacts_path, class: "link-light" %>
  </div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Home", root_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <form class="d-flex">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if current_user == nil %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
            </li>
          <% else %>
            <% if current_user.analyst? %>
              <%= link_to "Awaiting approval", awaiting_approval_path, class: "nav-link" %><p style="color:red;"><%= @aa_count %></p>
              <%= link_to "Summary", summary_path, class: "nav-link" %>
              <%= link_to "Notifications", notifications_path, class: "nav-link" %><p style="color:red;"><%= @analyst_notifications %></p>
            <% else %>
              <li class="nav-item">
                <%= link_to "My Requests", work_requests_path, class: "nav-link" %>
              </li>
              <%= link_to "Notifications", notifications_path, class: "nav-link" %><p style="color:red;"><%= @my_notifications %></p>
            <% end %>
            <li class="nav-item">
              <%= link_to "Edit profile", edit_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "nav-link" %>
            </li>
          <% end %>

        </ul>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkManagementSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <br>
    <%= render 'layouts/footer' %>
  </body>
</html>